version: '3.8'
services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar inMemory -sharedDb"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   networks:
      - dynamodb-local-network
   
 dynamodb-admin:
   image: aaronshaf/dynamodb-admin
   environment:
     - DYNAMO_ENDPOINT=http://dynamodb-local:8000
   ports:
     - "8001:8001"
   depends_on:
     - dynamodb-local
   networks:
     - dynamodb-local-network

networks:
  dynamodb-local-network:
    driver: bridge