service: iaew-tpi

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x 
  stage: dev
  region: us-east-1
  environment: ${file(environments/environment_${self:custom.currentStage}_ssm.yaml)}

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  getProveedor:
    handler: src/getProveedor.handler
    events:
      - http:
          path: /proveedores/{proveedorId}
          method: get

custom:
  currentStage: ${opt:stage, self:provider.stage}
