service: iaew-tpi

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x 
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  getProveedor:
    handler: src/getProveedor.handler
    events:
      - http:
          path: /proveedores
          method: get
  createProveedor:
    handler: src/createProveedor.handler
    events:
      - http:
          path: /proveedores
          method: post
  updateProveedor:
    handler: src/updateProveedor.handler
    events:
      - http:
          path: /proveedores/{proveedor_id}
          method: put
  deleteProveedor:
    handler: src/deleteProveedor.handler
    events:
      - http:
          path: /proveedores/{proveedor_id}
          method: delete
  
  getServicio:
    handler: src/getServicio.handler
    events:
      - http:
          path: /proveedores/{provedor_id}/servicios
          method: get
  createServicio:
    handler: src/createServicio.handler
    events:
      - http:
          path: /proveedores/{provedor_id}/servicios
          method: post
  updateServicio:
    handler: src/updateServicio.handler
    events:
      - http:
          path: /proveedores/{provedor_id}/servicios/{servicio_id}
          method: put
  deleteServicio:
    handler: src/deleteServicio.handler
    events:
      - http:
          path: /proveedores/{provedor_id}/servicios/{servicio_id}
          method: delete

resources:
  Resources:
    Proveedores:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Proveedores
        AttributeDefinitions:
          - AttributeName: proveedor_id
            AttributeType: S
        KeySchema:
          - AttributeName: proveedor_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    Servicios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Servicios
        AttributeDefinitions:
          - AttributeName: servicios_id
            AttributeType: S
        KeySchema:
          - AttributeName: servicios_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
